chore: update test

diff --git a/.github/workflows/continuous-integration.yaml b/.github/workflows/continuous-integration.yaml
--- a/.github/workflows/continuous-integration.yaml
+++ b/.github/workflows/continuous-integration.yaml
@@ -454,25 +454,20 @@ jobs:
   # ----------------
   start-runner-gpu-linux:
       needs: [matrix-preparation]
-      name: Start SLAB runner (GPU)
+      name: Start GPU SLAB runner
+      # This label is irrelevant once the SLAB runner starts.
       runs-on: ubuntu-24.04
+      
       timeout-minutes: 15
       outputs:
         label: ${{ steps.start-slab-runner.outputs.label }}
       steps:
-        - name: Checkout Code
-          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
-
         - name: Configure AWS credentials
-          uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
+          uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
           with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ${{ secrets.AWS_REGION }}
-
-        - name: Who am I?
-          run: aws sts get-caller-identity
-
               
         - name: Start SLAB GPU runner
           id: start-slab-runner
@@ -486,79 +481,98 @@ jobs:
               backend: aws
               profile: gpu_ciprofile 
 
-        - name: Check GPU availability
-          if: ${{ !cancelled() }}
-          run: |
-            echo "Checking for GPU..."
-            which nvidia-smi || echo "nvidia-smi not found"
-            nvidia-smi || echo "GPU drivers not working"
-                    
-  # gpu-tests:
-  #   name: GPU tests (Python ${{ matrix.python_version }})
-  #   needs: [start-runner-gpu-linux]
-  #   runs-on: ${{ needs.start-runner-gpu-linux.outputs.label }}
-  #   container:
-  #     image: ubuntu:24.04
-  #   # Force all environments to use the Bash shell for all 'run' commands
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       python_version: ${{ fromJSON(format('[%s]', needs.matrix-preparation.outputs.gpu-python-versions | join(','))) }}
-
-  #   steps:
-  #     # Replace default archive.ubuntu.com from docker image with fr mirror
-  #     # original archive showed performance issues and is farther away
-  #     - name: Docker container related setup and git installation
-  #       run: |
-  #         TZ=Europe/Paris
-  #         echo "TZ=${TZ}" >> "$GITHUB_ENV"
-  #         ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
-  #         sed -i 's|^deb http://archive|deb http://fr.archive|g' /etc/apt/sources.list
-  #         apt update && apt install git git-lfs -y
-
-
-
-      # # Checkout the code
-      # # 'fetch-depth' is set to 0 in order to fetch all tags (used for generating the changelog)
-      # - name: Checkout Code
-      #   uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
-      #   with:
-      #     fetch-depth: 0
-
-      # - name: Set up Python ${{ matrix.python_version }}
-      #   uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
-      #   id: setup-python
-      #   with:
-      #     python-version: ${{ matrix.python_version }}
-
-
-      # - name: Install dependencies
-      #   id: install-deps
-      #   run: |
-      #     make setup_env
-      #     pip install pytest
-      #     echo
-      #     echo "Using these tools:"
-      #     which python3
-      #     which pip3
-      #     echo
-      # - name: Run GPU tests
-      #   shell: bash +e {0}
-      #   run: make pytest_gpu
+  GPU-availability:
+    name: GPU Availability
+    runs-on: ${{ needs.start-runner-gpu-linux.outputs.label }}
+    needs: start-runner-gpu-linux
     
+    steps:
+      - name: Check GPU availability
+        run: |
+          echo "Checking for GPU..."
+          which nvidia-smi || echo "nvidia-smi not found"
+          nvidia-smi || echo "nvidia-smi failed"
+          nvcc --version || echo "nvcc --version failed"
+
+      - name: Check OS information
+        run: |
+          echo "Checking for machine OS information..."
+          cat /etc/os-release
+      - name: Check pre-installed python version
+        run: |
+          echo "Python3 version: $(python3 --version 2>&1)"
+
+
+  GPU-tests:
+    name: Run GPU tests (Python ${{ matrix.python_version }})
+    runs-on: ${{ needs.start-runner-gpu-linux.outputs.label }}
+    needs: [start-runner-gpu-linux, GPU-availability]
+    strategy:
+      matrix:
+        python_version: [3.8]
+
+    steps:
+      - name: Set Home
+        run: |
+          echo "Set HOME=$(pwd)"
+          echo "HOME=$(pwd)" >> $GITHUB_ENV
+
+      - name: Disable LFS download by default
+        run: |
+
+          apt-get update
+          apt-get install git-lfs
+
+          git lfs install --skip-smudge
+
+      - name: Checkout code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+
+      - name: Pull LFS files
+        run: |
+          git lfs pull --include "tests/data/**, src/concrete/ml/pandas/_client_server_files/**" --exclude  ""
+
+      - name: Set up Python ${{ matrix.python_version }}
+        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
+        id: setup-python
+        with:
+          python-version: ${{ matrix.python_version }}
+
+      - name: Install Deps
+        id: install-deps
+        run: |
+          echo "Using these tools: $(which python3), $(which pip3)"      
+          ./script/make_utils/setup_os_deps.sh
+          make setup_env
+
+      - name: Install GPU concrete-python
+        id: install-gpu-concrete-python
+        run: |
+          # Show CP version
+          poetry run pip show concrete-python || echo "concrete-python not installed"
+          poetry run pip uninstall -y concrete-python
+
+          
+          # poetry run pip install --extra-index-url https://pypi.zama.ai/gpu concrete-python
+          poetry run pip install --extra-index-url https://pypi.zama.ai/gpu concrete-python==2.10.0
+
+          # Show new CP version
+          poetry run pip show concrete-python || echo "concrete-python not installed"
+
+
+      - name: 🚀 Run GPU Tests
+        run: |
+          make pytest_gpu
 
   stop-runner-gpu-linux:
     name: Stop SLAB runner (GPU)
-    needs: [start-runner-gpu-linux]
+    needs: [start-runner-gpu-linux, GPU-tests, GPU-availability]
     runs-on: ubuntu-24.04
     timeout-minutes: 2
     if: ${{ always() && (needs.start-runner-gpu-linux.result != 'skipped') }}
     steps:
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
+        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
