chore: temporarily enable trigger from another branch

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -118,16 +118,16 @@ jobs:
           token: ${{ secrets.BOT_TOKEN }}
 
       # Make sure that the target branch is main
-      - name: Stop if branch is not main
-        id: check-branch-is-main
-        if: ${{ always() && !cancelled() }}
-        env:
-          BRANCH_IS_MAIN: ${{ github.ref_name == 'main'}} 
-        run: |
-          if [[ "${BRANCH_IS_MAIN}" != "true" ]]; then
-            echo "Release cannot be done: target branch is not main"
-            exit 1
-          fi
+      # - name: Stop if branch is not main
+      #   id: check-branch-is-main
+      #   if: ${{ always() && !cancelled() }}
+      #   env:
+      #     BRANCH_IS_MAIN: ${{ github.ref_name == 'main'}} 
+      #   run: |
+      #     if [[ "${BRANCH_IS_MAIN}" != "true" ]]; then
+      #       echo "Release cannot be done: target branch is not main"
+      #       exit 1
+      #     fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
@@ -182,7 +182,7 @@ jobs:
 
       # Run the CI on different Python versions
       - name: Run CI with different Python versions
-        uses: ./.github/workflows/continuous-integration.yaml
+        uses: .github/workflows/continuous-integration.yaml
         with:
           event-name: "release"
 
