chore: fix reusable workflow syntax

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -81,6 +81,7 @@ jobs:
 
   # Check that everything is up to date and run all non-flaky tests on different Python versions 
   release-checks:
+    name: Install deps and run checks
     needs: [start-runner-linux]
 
     runs-on: ${{ needs.start-runner-linux.outputs.label }}
@@ -118,16 +119,16 @@ jobs:
           token: ${{ secrets.BOT_TOKEN }}
 
       # Make sure that the target branch is main
-      # - name: Stop if branch is not main
-      #   id: check-branch-is-main
-      #   if: ${{ always() && !cancelled() }}
-      #   env:
-      #     BRANCH_IS_MAIN: ${{ github.ref_name == 'main'}} 
-      #   run: |
-      #     if [[ "${BRANCH_IS_MAIN}" != "true" ]]; then
-      #       echo "Release cannot be done: target branch is not main"
-      #       exit 1
-      #     fi
+      - name: Stop if branch is not main
+        id: check-branch-is-main
+        if: ${{ always() && !cancelled() }}
+        env:
+          BRANCH_IS_MAIN: ${{ github.ref_name == 'main'}} 
+        run: |
+          if [[ "${BRANCH_IS_MAIN}" != "true" ]]; then
+            echo "Release cannot be done: target branch is not main"
+            exit 1
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
@@ -180,15 +181,19 @@ jobs:
         run: |
           ./script/actions_utils/check_branch_not_remote.sh --branch_name "${{ env.RELEASE_BRANCH_NAME }}"
 
-      # Run the CI on different Python versions
-      - name: Run CI with different Python versions
-        uses: .github/workflows/continuous-integration.yaml
-        with:
-          event-name: "release"
-
+  # The caller workflow's job (here 'release-tests') do not need to run on the current runner as 
+  # the reusable workflow (here 'continuous-integration.yaml') uses its own runner
+  release-tests:
+    name: Run tests
+    needs: [start-runner-linux, release-checks]
+    uses: ./.github/workflows/continuous-integration.yaml
+    secrets: inherit
+    with:
+      event_name: "release"
 
   release-pushes:
-    needs: [start-runner-linux, release-checks]
+    name: Push new tag and branch
+    needs: [start-runner-linux, release-tests]
 
     runs-on: ${{ needs.start-runner-linux.outputs.label }}
     # Run in a clean container
@@ -221,10 +226,10 @@ jobs:
   # done through the 'PUBLIC_RELEASE_IMAGE_BASE' image. The private image is also used to list all 
   # tags easily
   release-package:
+    name: Release package and artifacts
     needs: [start-runner-linux, release-pushes]
     outputs:
       report: ${{ steps.report.outputs.report || 'Did not run.' }}
-    name: Package and artifacts release
     runs-on: ${{ needs.start-runner-linux.outputs.label }}
     env:
       PRIVATE_RELEASE_IMAGE_BASE: ghcr.io/zama-ai/concrete-ml
